### PR TITLE
Get remediation conditions from config map

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Will check node conditions and if node has at least one
remediation condition, the code will start remediation
proccess.

### CODE REVIEW

**Comment by beekhof** [comment]
Looks good once the tests are passing again.

Do we want the option of fencing when some combination of Conditions is satisfied, or just when any one of them is?

**Comment by cynepco3hahue** [comment]
@beekhof I think we can extend it in the future, for now, I just check if any one of them exists longer than specified timeout under the node conditions.

Will check tests today.

**Comment by cynepco3hahue** [comment]
@beekhof And it is cool that we have at least some basic tests :smile:

**Comment by cynepco3hahue** [comment]
ci test please

**Comment by cynepco3hahue** [comment]
Looks like os-3.11 is broken, need to check what happened.

**Pull request merged**
